TOPIC_KEYWORDS = {
    "religious-referential": {
        "ar": [
            "الله", "التوحيد", "الإسلام", "الإيمان", "القدَر", "النصر", "التوكّل", "الابتلاء",
            "الكفر", "الشرك", "الآخرة", "الدعاء", "التوبة", "الباطل", "الحق", "القرآن",
            "السنّة", "الحديث", "الفتوى", "الشريعة", "الحلال", "الحرام", "الفقه", "التفسير",
            "العلماء", "الاجتهاد", "الإجماع", "القدس", "المسجد الأقصى", "الكعبة", "مكّة",
            "المدينة", "بيت المقدس", "الأرض المباركة", "الرباط", "العدل", "الرحمة", "الأخوّة",
            "الصبر", "التقوى", "الأمانة", "الظلم", "الشهادة", "الشهداء", "الفداء",
            "النبي محمد", "صلاح الدين", "عمر بن الخطاب", "الأنبياء", "عيسى", "المسيح", "موسى",
            "إبراهيم", "المهدي", "آل البيت", "الخلفاء", "دعا", "دعَوْا", "يدعو", "يدعون",
            "اُدعُ", "ادعوا", "دعاء", "دعوة", "داعٍ", "داعون", "صلّى", "صلّوا", "يُصلّي",
            "يُصلّون", "صَلِّ", "صلاة", "تصلية", "مُصلٍّ", "مُصلّون", "استغفر", "استغفروا",
            "يستغفر", "يستغفرون", "استغفار", "مستغفِر", "تضرّع", "تضرّعوا", "يتضرّع",
            "يتضرّعون", "متضرّع", "توكّل", "توكّلوا", "يتوكّل", "يتوكّلون", "متوكّل", "تاب",
            "تابوا", "يتوب", "يتوبون", "تُبْ", "توبوا", "توبة", "تائب", "شكر", "شكروا", "يشكر",
            "يشكرون", "اشكر", "اشكروا", "شكران", "شاكر", "صبر", "صبروا", "يصبر", "يصبرون",
            "اصبر", "اصبروا", "صبران", "صابر", "ابتهل", "ابتهلوا", "يبتهل", "يبتهلون",
            "ابتهال", "مبتهِل", "ذكر", "ذكروا", "يذكر", "يذكرون", "اذكر", "اذكروا", "ذِكر",
            "ذِكرى", "ذاكر", "زكّى", "زكّوا", "يُزكّي", "يُزكّون", "زَكِّ", "تزكية", "زكاة",
            "مُزكٍّ", "اعتكف", "اعتكفوا", "يعتكف", "يعتكفون", "اعتكاف", "معتكِف", "أفتى",
            "أفتوا", "يُفتي", "يُفتون", "أَفتِ", "إفتاء", "فتوى", "مُفتٍ", "مُفتى به", "حرَّم",
            "حرَّموا", "يُحرِّم", "يُحرِّمون", "حرِّم", "حرِّموا", "تحريم", "مُحرِّم",
            "مُحرَّم", "أحلّ", "أحلّوا", "يُحِلّ", "يُحِلّون", "أَحِلَّ", "إحلال", "مُحِلّ",
            "مُحَلَّل", "أجاز", "أجازوا", "يُجيز", "يُجيزون", "أَجِزْ", "إجازة", "جواز",
            "مُجيز", "مُجاز", "نصّ", "نصّوا", "يَنُصّ", "يَنُصّون", "نُصَّ", "ناصٌّ", "منصوص",
            "اجتهد", "اجتهدوا", "يجتهد", "يجتهدون", "اجتهاد", "مجتهِد", "استنبط", "استنبطوا",
            "يستنبط", "يستنبطون", "استنباط", "مستنبِط", "فسَّر", "فسَّروا", "يُفسِّر",
            "يُفسِّرون", "فسِّر", "فسِّروا", "تفسير", "مُفسِّر", "مُفسَّر", "علَّم", "علَّموا",
            "يُعلِّم", "يُعلِّمون", "علِّم", "علِّموا", "تعليم", "مُعلِّم", "مُعلَّم", "كفَّر",
            "كفَّروا", "يُكفِّر", "يُكفِّرون", "كفِّر", "تكفير", "مُكفِّر", "مُكفَّر", "فسَق",
            "فسقوا", "يَفسُق", "يَفسُقون", "فسق", "فاسق", "مفسوق", "ظلَم", "ظلموا",
            "يَظلِم", "يَظلِمون", "ظُلم", "ظالم", "مظلوم", "آمن", "يؤمن", "آمنوا", "إيمان",
            "مؤمن", "شهد", "يشهد", "اشهد", "اشهدوا", "شهادة", "شاهد", "أشهد", "يُشهِد",
            "أَشهِد", "إشهاد", "مُشهِد", "بشَّر", "يُبشِّر", "بشِّر", "بشِّروا", "تبشير",
            "مُبشِّر", "حمد", "يحمد", "احمد", "احمدوا", "حامد", "سبّح", "يُسبِّح", "سبِّح",
            "سبِّحوا", "تسبيح", "مُسبِّح", "أقسم", "يُقسِم", "أَقسِم", "قَسَم", "إقسام",
            "مُقسِم", "تبرّأ", "يتبرّأ", "تبرّأوا", "تبرّؤ", "متبرِّئ", "لعن", "يَلعَن",
            "اِلعَن", "العنوا", "لاعن", "استنكر", "يستنكر", "استنكار", "مستنكِر", "استغاث",
            "يستغيث", "استغث", "استغيثوا", "استغاثة", "مستغيث", "ابتلي", "يُبتَلى", "ابتلاء",
            "مبتلًى", "نجا", "ينجو", "انجُ", "انجوا", "نجاة", "ناجٍ", "رجا", "يرجو", "ارجُ",
            "ارجوا", "رجاء", "راجٍ", "أنذر", "يُنذِر", "أَنذِر", "إنذار", "مُنذِر", "انتمى",
            "ينتمي", "انتماء", "منتمٍ", "وحَّد", "يُوحِّد", "توحيد", "مُوحِّد", "مُوحَّد",
            "تآخى", "يتآخى", "تآخٍ", "متآخٍ", "تضامن", "يتضامن", "متضامن", "انتصر", "ينتصر",
            "انتصار", "منتصِر", "ثبت", "يثبت", "ثبات", "ثابت", "رابط", "يُرابِط", "مرابطة",
            "مُرابِط", "جاهد", "يجاهد", "جهاد", "مجاهِد", "ضحّى", "يُضحّي", "تضحية", "مُضحٍّ",
            "استشهد", "يستشهد", "استشهاد", "مستشهِد", "كافح", "يكافح", "كفاح", "مكافِح", "صمد",
            "يصمد", "صمود", "صامد", "أخلص", "يُخلِص", "إخلاص", "مُخلِص", "تفانى", "يتفانى",
            "تفانٍ", "متفانٍ", "فدى", "يفدي", "فداء", "فادٍ", "عقد", "يعقد", "عاقِد",
        ],
        "en": [
            "God", "Faith", "Islam", "Judaism", "Christianity", "Zionism", "Evangelical",
            "Torah", "Bible", "Quran", "Monotheism", "Prophecy", "Jerusalem", "Al-Aqsa",
            "Temple Mount", "Holy Land", "Sacred", "Promised Land", "Covenant",
            "Chosen People", "Abrahamic", "Halal", "Kosher", "Crusade", "Justice", "Mercy",
            "Morality", "Martyrdom", "Sacrifice", "Righteousness", "Sin", "Redemption",
            "Conscience", "Forgiveness", "Compassion", "Blasphemy", "Clergy", "Imam", "Rabbi",
            "Pope", "Ummah", "Interfaith", "Sect", "Fatwa", "Hajj", "Pray", "Prays", "Prayed",
            "Praying", "Prayer", "Prayers", "Bless", "Blesses", "Blessed", "Blessing",
            "Blessings", "Worship", "Worships", "Worshipped", "Worshipping", "Fasts",
            "Fasted", "Fasting", "Martyr", "Martyred", "Martyrs", "Sacrifices", "Sacrificed",
            "Sacrificing", "Repent", "Repents", "Repented", "Repenting", "Repentance",
            "Witness", "Witnesses", "Witnessed", "Witnessing", "Testify", "Testifies",
            "Testified", "Testifying", "Testimony", "Preach", "Preaches", "Preached",
            "Preaching", "Preacher", "Sanctify", "Sanctifies", "Sanctified", "Sanctifying",
            "Sanctification", "Condemn", "Condemns", "Condemned", "Condemning", "Condemnation",
            "Justify", "Justifies", "Justified", "Justifying", "Justification", "Blaspheme",
            "Blasphemes", "Blasphemed", "Blaspheming", "Desecrate", "Desecrates", "Desecrated",
            "Desecrating", "Desecration", "Profane", "Profanes", "Profaned", "Profaning",
            "Profanity", "Interpret", "Interprets", "Interpreted", "Interpreting",
            "Interpretation", "Invoke", "Invokes", "Invoked", "Invoking", "Invocation",
            "Ordain", "Ordains", "Ordained", "Ordaining", "Ordination", "Proclaim",
            "Proclaims", "Proclaimed", "Proclaiming", "Proclamation", "Unite", "Unites",
            "United", "Uniting", "Unity", "Stands", "Stood", "Standing", "Resist",
            "Resists", "Resisted", "Resisting", "Resistance", "Persevere", "Perseveres",
            "Persevered", "Persevering", "Perseverance", "Endure", "Endures", "Endured",
            "Enduring", "Endurance", "Liberate", "Liberates", "Liberated", "Liberating",
            "Liberation", "Dedicate", "Dedicates", "Dedicated", "Dedicating", "Dedication",
            "Pledge", "Pledges", "Pledged", "Pledging", "Vows", "Vowed", "Vowing",
            "Belong", "Belongs", "Belonged", "Belonging", "Identify", "Identifies",
            "Identified", "Identifying", "Identity", "Affirm", "Affirms", "Affirmed",
            "Affirming", "Affirmation", "Convert", "Converts", "Converted", "Converting",
            "Conversion", "Prophesy", "Prophesies", "Prophesied", "Prophesying", "Fulfill",
            "Fulfills", "Fulfilled", "Fulfilling", "Fulfillment", "Reveal", "Reveals",
            "Revealed", "Revealing", "Revelation", "Warn", "Warns", "Warned", "Warning",
            "Redeem", "Redeems", "Redeemed", "Redeeming", "Resurrect", "Resurrects",
            "Resurrected", "Resurrecting", "Resurrection", "Anoint", "Anoints", "Anointed",
            "Anointing", "Anointment", "Consecrate", "Consecrates", "Consecrated",
            "Consecrating", "Illuminate", "Illuminates", "Illuminated", "Illuminating",
            "Illumination", "Righteously", "Glorify", "Glorifies", "Glorified",
            "Glorifying", "Glory",
        ],
    },
    "diplomatic-relational": {
        "ar": [
            "الاحتلال", "الصهيونية", "العدوان", "الإبادة", "المجزرة", "الحصار",
            "التطهير العرقي", "النكبة", "الاستيطان", "التهجير", "الأسرى", "الرهائن", "القصف",
            "الحرب", "جرائم الحرب", "المقاومة", "الجهاد", "طوفان الأقصى", "حماس", "حزب الله",
            "الفصائل", "الانتفاضة", "التحرير", "سيف القدس", "العودة", "التطبيع",
            "اتفاقيات إبراهيم", "الأمم المتحدة", "مجلس الأمن", "الفيتو", "محكمة العدل الدولية",
            "الجنائية الدولية", "وقف إطلاق النار", "الهدنة", "المفاوضات", "السلام", "التضامن",
            "المساعدات", "الحلّ", "الاعتراف", "نتنياهو", "بايدن", "ترامب", "إيران", "السعودية",
            "مصر", "تركيا", "قطر", "الأردن", "الجامعة العربية", "منظمة التعاون الإسلامي",
            "الحكّام العرب", "التواطؤ", "الخيانة", "المؤامرة", "أدان", "أدانوا", "يُدين",
            "يُدينون", "أَدِنْ", "أدينوا", "إدانة", "مُدين", "مُدان", "استنكر", "استنكروا",
            "يستنكر", "يستنكرون", "استنكار", "مستنكِر", "اتّهم", "اتّهموا", "يتّهم", "يتّهمون",
            "اتّهام", "متّهِم", "متّهَم", "طالب", "طالبوا", "يُطالِب", "يُطالِبون", "طالِب",
            "مطالبة", "مُطالِب", "مُطالَب", "حاسب", "حاسبوا", "يُحاسِب", "يُحاسِبون", "حاسِب",
            "محاسبة", "مُحاسِب", "مُحاسَب", "ساءل", "ساءلوا", "يُساءِل", "يُساءِلون", "ساءِل",
            "مساءلة", "مُساءِل", "مُساءَل", "فضح", "فضحوا", "يفضح", "يفضحون", "افضح", "افضحوا",
            "فاضح", "مفضوح", "كشف", "كشفوا", "يكشف", "يكشفون", "اكشف", "اكشفوا", "كاشف",
            "مكشوف", "جرَّم", "جرَّموا", "يُجرِّم", "يُجرِّمون", "جرِّم", "تجريم", "مُجرِّم",
            "مُجرَّم", "وثَّق", "وثَّقوا", "يُوثِّق", "يُوثِّقون", "وثِّق", "وثِّقوا", "توثيق",
            "مُوثِّق", "مُوثَّق", "أدلى", "أدلوا", "يُدلي", "يُدلون", "أَدلِ", "إدلاء",
            "مُدلٍ", "أعلن", "أعلنوا", "يُعلِن", "يُعلِنون", "أَعلِن", "إعلان", "مُعلِن",
            "مُعلَن", "رفض", "رفضوا", "يرفض", "يرفضون", "ارفض", "ارفضوا", "رافض", "مرفوض",
            "انتقد", "انتقدوا", "ينتقد", "ينتقدون", "انتقاد", "منتقِد", "منتقَد", "شجب",
            "شجبوا", "يشجب", "يشجبون", "اشجب", "اشجبوا", "شاجب", "تحالف", "يتحالف", "متحالِف",
            "دعم", "يدعم", "دعامة", "داعِم", "ناصر", "يُناصِر", "مناصرة", "مُناصِر", "أسند",
            "يُسنِد", "إسناد", "مُسنِد", "وقف مع", "يقف مع", "وقوف مع", "واقف", "وحَّد",
            "يُوحِّد", "توحيد", "مُوحِّد", "قاطع", "يُقاطِع", "مقاطعة", "مُقاطِع", "ساند",
            "يُساند", "مساندة", "مُساند", "انحاز", "ينحاز", "انحياز", "منحاز", "تبنّى",
            "يتبنّى", "تبنٍّ", "متبنٍّ", "تضامن", "يتضامن", "متضامن", "احتضن", "يحتضن",
            "احتضان", "محتضِن", "فاوض", "يُفاوِض", "مفاوضة", "مُفاوِض", "مُفاوَض", "توسَّط",
            "يتوسَّط", "توسُّط", "متوسِّط", "تفاوض", "يتفاوض", "متفاوِض", "أوقف", "يُوقِف",
            "إيقاف", "مُوقِف", "هادن", "يُهادِن", "مهادنة", "مُهادِن", "اعترف", "يعترف",
            "اعتراف", "معترِف", "رعى", "يرعى", "رعاية", "راعٍ", "مرعيّ", "وسَّط", "يُوسِّط",
            "توسيط", "مُوسِّط", "عرض", "يعرض", "عارض", "معروض", "تبادل", "يتبادل", "متبادَل",
            "استقبل", "يستقبل", "استقبال", "مستقبِل", "رفع", "يرفع", "رافع", "قدَّم",
            "يُقدِّم", "تقديم", "مُقدِّم", "هدَّد", "يُهدِّد", "تهديد", "مُهدِّد", "توعَّد",
            "يتوعَّد", "توعُّد", "متوعِّد", "أنذر", "يُنذِر", "إنذار", "مُنذِر", "هاجم",
            "يهاجم", "هجوم", "مهاجِم", "ردَّ", "يردّ", "ردّ", "رادّ", "صعَّد", "يُصعِّد",
            "تصعيد", "مُصعِّد", "استهدف", "يستهدف", "استهداف", "مستهدِف", "حاصر", "يُحاصِر",
            "محاصرة", "مُحاصِر", "اخترق", "يخترق", "اختراق", "مخترِق", "أسقط", "يُسقِط",
            "إسقاط", "مُسقِط", "واجه", "يُواجِه", "مواجهة", "مُواجِه", "تصدَّى", "يتصدَّى",
            "تصدٍّ", "متصدٍّ", "ضرب", "يضرب", "ضارب", "اعتقل", "يعتقل", "اعتقال", "معتقِل",
            "هجَّر", "يُهجِّر", "تهجير", "مُهجِّر",
        ],
        "en": [
            "Genocide", "Occupation", "Apartheid", "Ethnic Cleansing", "War Crimes", "Siege",
            "Bombing", "Displacement", "Hostages", "Prisoners", "Ceasefire", "Massacre",
            "Resistance", "Terrorism", "Hamas", "Hezbollah", "Jihad", "Intifada", "Liberation",
            "Self-Defense", "International Law", "ICJ", "ICC", "UN", "Veto", "Sanctions",
            "Two-State", "Recognition", "UNRWA", "Humanitarian", "Normalization",
            "Abraham Accords", "Diplomacy", "Netanyahu", "Biden", "Trump", "AIPAC", "Congress",
            "Complicity", "Double Standards", "Islamophobia", "Antisemitism", "Settler",
            "Proxy War", "Axis of Resistance", "Condemn", "Condemns", "Condemned",
            "Condemning", "Condemnation", "Demand", "Demands", "Demanded", "Demanding",
            "Denounce", "Denounces", "Denounced", "Denouncing", "Denunciation", "Prosecute",
            "Prosecutes", "Prosecuted", "Prosecuting", "Prosecution", "Sanction", "Sanctioned",
            "Sanctioning", "Expose", "Exposes", "Exposed", "Exposing", "Exposure", "Accuse",
            "Accuses", "Accused", "Accusing", "Accusation", "Challenge", "Challenges",
            "Challenged", "Challenging", "Reject", "Rejects", "Rejected", "Rejecting",
            "Rejection", "Oppose", "Opposes", "Opposed", "Opposing", "Opposition", "Protest",
            "Protests", "Protested", "Protesting", "Hold Accountable", "Held accountable",
            "Holding accountable", "Accountability", "Investigate", "Investigates",
            "Investigated", "Investigating", "Investigation", "Supports",
            "Supported", "Supporting", "Ally", "Allies", "Allied", "Allying", "Alliance",
            "Boycott", "Boycotts", "Boycotted", "Boycotting", "Mobilize", "Mobilizes",
            "Mobilized", "Mobilizing", "Mobilization", "Recognize", "Recognizes", "Recognized",
            "Recognizing", "Endorse", "Endorses", "Endorsed", "Endorsing", "Endorsement",
            "Funds", "Funded", "Funding", "Unite", "Unites", "United", "Uniting",
            "Unity", "Coordinate", "Coordinates", "Coordinated", "Coordinating",
            "Coordination", "Empower", "Empowers", "Empowered", "Empowering", "Empowerment",
            "Negotiate", "Negotiates", "Negotiated", "Negotiating", "Negotiation", "Mediate",
            "Mediates", "Mediated", "Mediating", "Mediation", "Broker", "Brokers", "Brokered",
            "Brokering", "Intervene", "Intervenes", "Intervened", "Intervening",
            "Intervention", "Impose", "Imposes", "Imposed", "Imposing", "Imposition",
            "Pressure", "Pressures", "Pressured", "Pressuring", "Facilitate", "Facilitates",
            "Facilitated", "Facilitating", "Facilitation", "Cease", "Ceases", "Ceased",
            "Ceasing", "Suspend", "Suspends", "Suspended", "Suspending", "Suspension",
            "Withdraw", "Withdraws", "Withdrew", "Withdrawing", "Withdrawal", "Threaten",
            "Threatens", "Threatened", "Threatening", "Threat", "Escalate", "Escalates",
            "Escalated", "Escalating", "Escalation", "Strike", "Strikes", "Struck", "Striking",
            "Retaliate", "Retaliates", "Retaliated", "Retaliating", "Retaliation", "Besiege",
            "Besieges", "Besieged", "Besieging", "Displace", "Displaces", "Displaced",
            "Displacing", "Targets", "Targeted", "Targeting", "Invade", "Invades",
            "Invaded", "Invading", "Invasion", "Occupy", "Occupies", "Occupied", "Occupying",
            "Massacres", "Massacred", "Massacring", "Commits", "Committed",
            "Committing", "Commitment", "Exterminate", "Exterminates", "Exterminated",
            "Exterminating", "Extermination",
        ],
    },
    "digital-influential": {
        "ar": [
            "هاشتاق", "تريند", "حملة", "مقاطعة", "تغريدة", "ريتويت", "منصة", "مقطع",
            "بثّ مباشر", "تفاعل", "متابعين", "مشاركة", "تعليق", "إعجاب", "خوارزمية", "الرواية",
            "الحقيقة", "الكذب", "التضليل", "البروباغندا", "الإعلام", "الإعلام البديل",
            "الصحفي", "التوثيق", "الشهادة", "الصورة", "الفيديو", "المصدر", "التحقّق",
            "الرقابة", "التأثير", "الرأي العام", "الوعي", "الضغط", "الصوت", "الصمت", "الموقف",
            "النصرة", "الاحتجاج", "المظاهرة", "العريضة", "التبرّع", "المؤثّر", "الناشط",
            "الشيخ الرقمي", "الداعية", "المراسل", "المتضامن", "الجيش الإلكتروني", "البوت",
            "الحظر", "التقييد", "نشر", "نشروا", "ينشر", "ينشرون", "انشر", "انشروا", "نشرة",
            "ناشر", "أعاد النشر", "يُعيد النشر", "أَعِد النشر", "إعادة نشر", "مُعيد النشر",
            "شارك", "شاركوا", "يُشارِك", "يُشارِكون", "شارِك", "مُشارِك", "بثَّ", "بثّوا",
            "يبثّ", "يبثّون", "ابثُث", "ابثّوا", "بثّ", "باثّ", "بثَّ مباشرة", "يبثّ مباشرة",
            "ابثُث مباشرة", "باثّ مباشر", "وثَّق", "وثَّقوا", "يُوثِّق", "يُوثِّقون", "وثِّق",
            "وثِّقوا", "توثيق", "مُوثِّق", "رفع", "رفعوا", "يرفع", "يرفعون", "ارفع", "ارفعوا",
            "رافع", "علَّق", "علَّقوا", "يُعلِّق", "يُعلِّقون", "علِّق", "علِّقوا", "مُعلِّق",
            "غرَّد", "غرَّدوا", "يُغرِّد", "يُغرِّدون", "غرِّد", "غرِّدوا", "تغريد", "مُغرِّد",
            "أضاف", "أضافوا", "يُضيف", "يُضيفون", "أَضِف", "أضيفوا", "إضافة", "مُضيف",
            "استشهد", "استشهدوا", "يستشهد", "يستشهدون", "استشهاد", "مستشهِد", "اقتبس",
            "اقتبسوا", "يقتبس", "يقتبسون", "اقتباس", "مقتبِس", "ذيَّل", "ذيَّلوا", "يُذيِّل",
            "يُذيِّلون", "ذيِّل", "تذييل", "مُذيِّل", "أطلق", "أطلقوا", "يُطلِق", "يُطلِقون",
            "أَطلِق", "إطلاق", "مُطلِق", "طلب", "طلبوا", "يطلب", "يطلبون", "اطلب", "اطلبوا",
            "طالب", "أثَّر", "يُؤثِّر", "أثِّر", "أثِّروا", "تأثير", "مُؤثِّر", "أقنع",
            "يُقنِع", "أَقنِع", "أقنعوا", "إقناع", "مُقنِع", "حشد", "يحشد", "احشد", "احشدوا",
            "تحشيد", "حاشد", "عبأ", "يُعبِّئ", "عبِّئ", "عبِّئوا", "تعبئة", "مُعبِّئ",
            "استنهض", "يستنهض", "استنهاض", "مستنهِض", "استنفر", "يستنفر", "استنفار", "مستنفِر",
            "حرَّك", "يُحرِّك", "حرِّك", "حرِّكوا", "تحريك", "مُحرِّك", "استفزَّ", "يستفزّ",
            "استفزاز", "مستفِزّ", "دفع", "يدفع", "ادفع", "ادفعوا", "دافع", "ألهم", "يُلهِم",
            "أَلهِم", "إلهام", "مُلهِم", "أثار", "يُثير", "أَثِر", "أثيروا", "إثارة", "مُثير",
            "شحن", "يشحن", "اشحن", "شاحن", "ضغط", "يضغط", "اضغط", "اضغطوا", "ضاغط", "كسب",
            "يكسب", "اكسب", "كاسب", "وجَّه", "يُوجِّه", "وجِّه", "وجِّهوا", "توجيه", "مُوجِّه",
            "روى", "يروي", "رواية", "راوٍ", "مرويّ", "أطَّر", "يُؤطِّر", "تأطير", "مُؤطِّر",
            "مُؤطَّر", "ضلَّل", "يُضلِّل", "تضليل", "مُضلِّل", "مُضلَّل", "كذَّب", "يُكذِّب",
            "تكذيب", "مُكذِّب", "مُكذَّب", "حقَّق", "يُحقِّق", "تحقيق", "مُحقِّق", "صحَّح",
            "يُصحِّح", "تصحيح", "مُصحِّح", "فنَّد", "يُفنِّد", "تفنيد", "مُفنِّد", "كشف",
            "يكشف", "كاشف", "تابع", "يتابع", "متابعة", "متابِع", "رصد", "يرصد", "راصد",
            "قيَّم", "يُقيِّم", "تقييم", "مُقيِّم", "سرَّب", "يُسرِّب", "تسريب", "مُسرِّب",
            "نظَّم", "يُنظِّم", "تنظيم", "مُنظِّم", "أدار", "يُدير", "إدارة", "مُدير", "فعَّل",
            "يُفعِّل", "تفعيل", "مُفعِّل", "وصَّل", "يُوصِّل", "توصيل", "مُوصِّل", "ضخَّم",
            "يُضخِّم", "تضخيم", "مُضخِّم", "راقب", "يُراقِب", "مراقبة", "مُراقِب", "بلَّغ",
            "يُبلِّغ", "تبليغ", "مُبلِّغ", "طعن", "يطعن", "طاعن", "أسَّس", "يُؤسِّس", "تأسيس",
            "مُؤسِّس",
        ],
        "en": [
            "Hashtag", "Trending", "Viral", "Retweet", "Repost", "Thread", "Livestream",
            "Engagement", "Followers", "Platform", "Algorithm", "Content", "Meme",
            "Infographic", "Timeline", "Narrative", "Propaganda", "Disinformation",
            "Misinformation", "Fact-Check", "Bias", "Censorship", "Shadow Ban", "Media",
            "Journalist", "Testimony", "Documentation", "Source", "Coverage", "Framing",
            "Influence", "Campaign", "Boycott", "BDS", "Petition", "Protest", "Rally",
            "Solidarity", "Awareness", "Mobilization", "Influencer", "Activist", "Bot",
            "Troll", "Echo Chamber", "Soft Power", "Encampment", "Deplatforming", "Posts",
            "Posted", "Posting", "Share", "Shares", "Shared", "Sharing", "Reposts", "Reposted",
            "Reposting", "Tweet", "Tweets", "Tweeted", "Tweeting", "Livestreams",
            "Livestreamed", "Livestreaming", "Upload", "Uploads", "Uploaded", "Uploading",
            "Stream", "Streams", "Streamed", "Streaming", "Broadcast", "Broadcasts",
            "Broadcasted", "Broadcasting", "Circulate", "Circulates", "Circulated",
            "Circulating", "Circulation", "Spread", "Spreads", "Spreading", "Amplify",
            "Amplifies", "Amplified", "Amplifying", "Amplification", "Publish", "Publishes",
            "Published", "Publishing", "Publication", "Tags", "Tagged", "Tagging",
            "Mobilize", "Mobilizes", "Mobilized", "Mobilizing", "Influences", "Influenced",
            "Influencing", "Persuade", "Persuades", "Persuaded", "Persuading", "Persuasion",
            "Inspire", "Inspires", "Inspired", "Inspiring", "Inspiration", "Raise", "Raises",
            "Raised", "Raising", "Calls", "Called", "Calling", "Pushes",
            "Pushed", "Pushing", "Force", "Forces", "Forced", "Forcing", "Galvanize",
            "Galvanizes", "Galvanized", "Galvanizing", "Engage", "Engages", "Engaged",
            "Engaging", "Educate", "Educates", "Educated", "Educating", "Education", "Awaken",
            "Awakens", "Awakened", "Awakening", "Motivate", "Motivates", "Motivated",
            "Motivating", "Motivation", "Narrate", "Narrates", "Narrated", "Narrating",
            "Frames", "Framed", "Debunk", "Debunks", "Debunked", "Debunking",
            "Counters", "Countered", "Countering", "Fact-checks", "Fact-checked",
            "Fact-checking", "Reveal", "Reveals", "Revealed", "Revealing", "Revelation",
            "Document", "Documents", "Documented", "Documenting", "Reports",
            "Reported", "Reporting", "Censor", "Censors", "Censored", "Censoring", "Delete",
            "Deletes", "Deleted", "Deleting", "Deletion", "Silence", "Silences", "Silenced",
            "Silencing", "Witness", "Witnesses", "Witnessed", "Witnessing", "Organize",
            "Organizes", "Organized", "Organizing", "Organization", "Coordinate",
            "Coordinates", "Coordinated", "Coordinating", "Coordination", "Launch", "Launches",
            "Launched", "Launching", "Trend", "Trends", "Trended", "Hashtags", "Hashtagged",
            "Hashtagging", "Follow", "Follows", "Followed", "Following", "Block", "Blocks",
            "Blocked", "Blocking", "Flag", "Flags", "Flagged", "Flagging", "Monitor",
            "Monitors", "Monitored", "Monitoring", "Verify", "Verifies", "Verified",
            "Verifying", "Verification",
        ],
    },
}

# Raw surface phrases that must never count toward a keyword hit, found by scanning
# tweet_classifications' corpus for the n-grams surrounding each keyword stem: the
# stemmer collapses these onto a keyword's stem, but they're unrelated proper nouns,
# not an inflection of the keyword.
#   "united states"/"united nations" -> stem "unit" (Unite/United/Uniting), ~10k hits,
#   essentially none of them about the concept of unity.
#   Arabic "قطاع" ("sector"/"strip", as in "قطاع غزة" = Gaza Strip) -> stem "قطع", same
#   root as "قاطع"/"مقاطعة" (boycott); "قطاع" never actually means boycott.
CONFOUND_PHRASES: dict[str, set[tuple[str, ...]]] = {
    "en": {("united", "states"), ("united", "nations")},
    "ar": {("قطاع",)},
}