export interface Tweet {
	id: string;
	text: string;
	created_at: string;
	like_count: number;
	retweet_count: number;
	reply_count: number;
	view_count: number;
	username: string;
	fullname: string;
	category: string;
}

export const mockTweets: Tweet[] = [
	{
		"id": "1102664557288411137",
		"text": "الارصاد الجوية : نحذر من تشكل السيول في بعض المناطق المنخفضة وخاصة \"الاغوار الشمالية \" بسبب حالة عدم الاستقرار الجوي التي ستؤثر على فلسطين يوم غدا الثلاثاء لذى نهيب بالغاء الرحلات او المسارات في المناطق الخطرة والمنحدرات",
		"created_at": "2019-03-04T20:18:11+00:00",
		"like_count": 5,
		"retweet_count": 0,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "diplomatic-relational"
	},
	{
		"id": "1722262432377344097",
		"text": "🇵🇰-🇲🇦| استقبل السيد ناصر بوريطة، اليوم بالرباط، السيد محمد سامي الرحمن، الذي قدم نسخا من أوراق اعتماده بصفته سفيرا مفوضا فوق العادة لجمهورية باكستان الإسلامية لدى صاحب الجلالة الملك محمد السادس. https://t.co/LX8SyEpIrM",
		"created_at": "2023-11-08T14:38:56+00:00",
		"like_count": 419,
		"retweet_count": 25,
		"reply_count": 8,
		"view_count": 12616,
		"username": "MarocDiplo_AR",
		"fullname": "الدبلوماسية المغربية 🇲🇦",
		"category": "diplomatic-relational"
	},
	{
		"id": "1062395524085702661",
		"text": "#Singapore: Meeting with Malaysian Prime Minister Mahathir Mohamad https://t.co/255YSx4Sjz https://t.co/UsgsenQLt5",
		"created_at": "2018-11-13T17:23:25+00:00",
		"like_count": 1294,
		"retweet_count": 392,
		"reply_count": 59,
		"view_count": 0,
		"username": "KremlinRussia_E",
		"fullname": "President of Russia",
		"category": "diplomatic-relational"
	},
	{
		"id": "1991610154383733028",
		"text": "#شاهد | مزارعون وأهالي يتصدون لهجوم المستوطنين على الأراضي الزراعية في منطقة السهل قرب بلدة بيت فوريك شرق نابلس https://t.co/hHoLUPcupq",
		"created_at": "2025-11-20T20:50:37+00:00",
		"like_count": 20,
		"retweet_count": 11,
		"reply_count": 0,
		"view_count": 792,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "1027244547410153472",
		"text": "🔴WATCH: a rocket fired from #Gaza shortly ago hit a building in the Israeli city of Sderot, causing an injury.\n\n7 more rockets were fired as part of this barrage.\n\n2 of them were intercepted by the Iron Dome aerial defence system. https://t.co/6aBRFfhVNn",
		"created_at": "2018-08-08T17:26:00+00:00",
		"like_count": 168,
		"retweet_count": 249,
		"reply_count": 31,
		"view_count": 0,
		"username": "IsraelMFA",
		"fullname": "Israel Foreign Ministry",
		"category": "digital-influential"
	},
	{
		"id": "1988200420800594330",
		"text": "🗓 Today, Angola celebrates the 5️⃣0️⃣- anniversary of independence.\n\nOn the same day, #RussiaAngola established diplomatic relations.\n\n🎉 We congratulate our colleagues and friends on their national holiday and on the anniversary of diplomatic relations!\n\nhttps://t.co/TR3vtrab4i https://t.co/Tq9WahKmaP",
		"created_at": "2025-11-11T11:01:33+00:00",
		"like_count": 189,
		"retweet_count": 49,
		"reply_count": 24,
		"view_count": 9286,
		"username": "mfa_russia",
		"fullname": "MFA Russia 🇷🇺",
		"category": "diplomatic-relational"
	},
	{
		"id": "965971734775156737",
		"text": "لدولة #قطر مواقف مشرفة من القضية الفلسطينية منذ نشأتها وخاصةً فيما يخص قطاع #غزة المحاصر\nحيث قامت على مدى السنوات الماضية بدعم صمود شعبها بمئات الملايين من الدولارات على شكل دعم مالي مباشر وغذاء ودواء ومحروقات\nوكل من ينفي هذه الحقيقة أو لا يراها فهو إما حاقدٌ أو متصهين !",
		"created_at": "2018-02-20T15:29:43+00:00",
		"like_count": 142,
		"retweet_count": 30,
		"reply_count": 14,
		"view_count": 0,
		"username": "Ali_AlQaradaghi",
		"fullname": "د. علي القره داغي",
		"category": "digital-influential"
	},
	{
		"id": "701476647426347008",
		"text": "مطالبات باستمرار الانتفاضة خلال تشييع الشهيد أبو الرب في جنين https://t.co/V7k8j13qQ3",
		"created_at": "2016-02-21T18:40:40+00:00",
		"like_count": 2,
		"retweet_count": 1,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "1134212497060368385",
		"text": "#صور | جانب من انعقاد أعمال قمة قادة دول مجلس التعاون لدول الخليج العربية الطارئة برئاسة #الملك_سلمان https://t.co/4naQVggBqq",
		"created_at": "2019-05-30T21:38:26+00:00",
		"like_count": 165,
		"retweet_count": 142,
		"reply_count": 4,
		"view_count": 0,
		"username": "KSAMOFA",
		"fullname": "وزارة الخارجية 🇸🇦",
		"category": "diplomatic-relational"
	},
	{
		"id": "1857904226380165179",
		"text": "“𝐌𝐚𝐲 𝐆𝐨𝐝 𝐟𝐫𝐞𝐞 𝐭𝐡𝐞 𝐡𝐨𝐬𝐭𝐚𝐠𝐞𝐬.” @Pontifex     \n\nThis week, a delegation of former hostages and families of those still held captive by Hamas met with the Pope at the Vatican, who said: \"I pray for you and your people.\"    \n\nMay his words echo true and may we see them safely at home.    \n\n@IsraelMFA @bringhomenow @IsraelinItaly @IsraelinHolySee \n\n📷: Vatican Media @VaticanNews",
		"created_at": "2024-11-16T21:51:00+00:00",
		"like_count": 32,
		"retweet_count": 9,
		"reply_count": 7,
		"view_count": 2476,
		"username": "IsraelinUSA",
		"fullname": "Embassy of Israel to the USA",
		"category": "diplomatic-relational"
	},
	{
		"id": "1870075383741067281",
		"text": "المتدخلون في الجلسة الختامية لاجتماع #المجلس_الأعلى لـ #مؤسسة_محمد_السادس_للعلماء_الأفارقة في دورته السنوية العادية السادسة\n\nParticipants in the closing session of the 6th annual ordinary session of the #Higher_Council of the Mohammed VI Foundation of African Oulema https://t.co/pCbmbxgjt2",
		"created_at": "2024-12-20T11:54:50+00:00",
		"like_count": 7,
		"retweet_count": 3,
		"reply_count": 0,
		"view_count": 231,
		"username": "fm6oaorg",
		"fullname": "مؤسسة محمد السادس للعلماء الأفارقة",
		"category": "diplomatic-relational"
	},
	{
		"id": "1840661818563293203",
		"text": "أدان المتحدث باسم الخارجیة، بشدة اعتداءات الکیان الصهیونی على خزانات الوقود ومحطة الکهرباء بمیناء #الحدیدة فی #الیمن، وأشاد بدعم الیمنیین المشرف للشعب الفلسطینی المظلوم،وحذر من عواقب قیام الکیان بإثارة الحروب وإشعالها على السلام والأمن الإقلیمیین والدولیین\nhttps://t.co/zmzyXXPufd https://t.co/vVewRWNdgl",
		"created_at": "2024-09-30T07:55:50+00:00",
		"like_count": 12,
		"retweet_count": 1,
		"reply_count": 2,
		"view_count": 1598,
		"username": "IRIMFA_AR",
		"fullname": "الخارجية الإيرانية",
		"category": "diplomatic-relational"
	},
	{
		"id": "793798128688332800",
		"text": "It's not only false, blatantly false, it also makes the achievement of peace harder.",
		"created_at": "2016-11-02T12:53:16+00:00",
		"like_count": 29,
		"retweet_count": 23,
		"reply_count": 6,
		"view_count": 0,
		"username": "IsraeliPM",
		"fullname": "Prime Minister of Israel",
		"category": "diplomatic-relational"
	},
	{
		"id": "24783636234",
		"text": "Be sure to tune in for Melania's second QVC show for \"Melania Timepieces & Jewelry\"  tonight, live from 9-10 pm on QVC http://bit.ly/aDdvKj",
		"created_at": "2010-09-17T18:55:21+00:00",
		"like_count": 19,
		"retweet_count": 31,
		"reply_count": 12,
		"view_count": 0,
		"username": "realDonaldTrump",
		"fullname": "Donald J. Trump",
		"category": "digital-influential"
	},
	{
		"id": "1820823630214844708",
		"text": "🇫🇮-🇲🇦 | زيارة السيد ناصر بوريطة اليوم إلى هلسنكي: اعتماد بيان مشترك في ختام المباحثات التي أجراها مع وزيرة الشؤون الخارجية لجمهورية فنلندا، السيدة إيلنا فالطونين.\n@Ulkoministerio \n @MoroccoInFIN https://t.co/C5uiMWGHYJ",
		"created_at": "2024-08-06T14:05:57+00:00",
		"like_count": 292,
		"retweet_count": 43,
		"reply_count": 5,
		"view_count": 5803,
		"username": "MarocDiplo_AR",
		"fullname": "الدبلوماسية المغربية 🇲🇦",
		"category": "diplomatic-relational"
	},
	{
		"id": "1403040979918151685",
		"text": "عاجل: يوسف كوهين زعيم الموساد السابق سيكشف امور جديدة تفضح النظام الإيراني بعد ساعة من الان على شاشات القناة ١٢ الصهيونية. تابعونا https://t.co/yPQSJkBwXV",
		"created_at": "2021-06-10T17:26:51+00:00",
		"like_count": 126,
		"retweet_count": 12,
		"reply_count": 24,
		"view_count": 0,
		"username": "EdyCohen",
		"fullname": "إيدي كوهين אדי כהן 🇮🇱",
		"category": "digital-influential"
	},
	{
		"id": "1885809344085684258",
		"text": "Once again, President Trump has shown our enemies he is not afraid to act.\n\nWith his leadership, we will make American national security STRONG again. \n\nWe cannot have peace without strength.",
		"created_at": "2025-02-01T21:55:58+00:00",
		"like_count": 7410,
		"retweet_count": 872,
		"reply_count": 559,
		"view_count": 152349,
		"username": "SpeakerJohnson",
		"fullname": "Speaker Mike Johnson",
		"category": "diplomatic-relational"
	},
	{
		"id": "721056523225579520",
		"text": "United States to announce $25 million in funding for @WorldBank's new financing initiative.\nMore info: https://t.co/et475DUa7U",
		"created_at": "2016-04-15T19:24:06+00:00",
		"like_count": 32,
		"retweet_count": 35,
		"reply_count": 14,
		"view_count": 0,
		"username": "StateDept",
		"fullname": "Department of State",
		"category": "diplomatic-relational"
	},
	{
		"id": "1158396121917612032",
		"text": "The President held a meeting with permanent members of the Security Council https://t.co/SdAIhziWfc https://t.co/EQ9sCO9GzS",
		"created_at": "2019-08-05T15:15:32+00:00",
		"like_count": 498,
		"retweet_count": 104,
		"reply_count": 65,
		"view_count": 0,
		"username": "KremlinRussia_E",
		"fullname": "President of Russia",
		"category": "diplomatic-relational"
	},
	{
		"id": "122138991591047168",
		"text": "#SecClinton hosts the President's Council on #Jobs and Competitiveness October 7. Live webcast 10:00 AM EDT: http://t.co/AboTgMgE",
		"created_at": "2011-10-07T02:39:39+00:00",
		"like_count": 0,
		"retweet_count": 9,
		"reply_count": 1,
		"view_count": 0,
		"username": "StateDept",
		"fullname": "Department of State",
		"category": "digital-influential"
	},
	{
		"id": "2009688944540299689",
		"text": "#متابعة | الرئيس التركي، رجب طيب أردوغان: \n\n- أوجه مشاعري التضامنية إلى جميع أبناء الشعب الفلسطيني الذي يحافظ على روح المقاومة والصمود مهما كانت الظروف\n\n- نريد إرسال كرافانات إلى غزة وطلبنا تدخل الأمم المتحدة والغرب، لكن الفرعون المسمى نتنياهو لا يهتم بهذه الأمور أبدا ولا يقبل بها",
		"created_at": "2026-01-09T18:09:17+00:00",
		"like_count": 3,
		"retweet_count": 8,
		"reply_count": 1,
		"view_count": 630,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "348090369193431040",
		"text": "Meeting with leaders of energy companies #SPIEF2013: development of global oil markets and attracting investment http://t.co/lkYEXshwIZ",
		"created_at": "2013-06-21T14:49:45+00:00",
		"like_count": 2,
		"retweet_count": 4,
		"reply_count": 0,
		"view_count": 0,
		"username": "KremlinRussia_E",
		"fullname": "President of Russia",
		"category": "diplomatic-relational"
	},
	{
		"id": "1675780166520303617",
		"text": "In a statement, the Jenin Brigades said that its fighters have blown up an Israeli military vehicle and prevented the advancement of invading Isreali soldiers in more than one area in #Jenin. #JeninUnderAttack  \nFOLLOW OUR LIVE BLOG: https://t.co/EuEUZibW2i https://t.co/KNdkyFUyYa",
		"created_at": "2023-07-03T08:15:00+00:00",
		"like_count": 4,
		"retweet_count": 2,
		"reply_count": 0,
		"view_count": 236,
		"username": "PalestineChron",
		"fullname": "The Palestine Chronicle",
		"category": "digital-influential"
	},
	{
		"id": "439079860082712576",
		"text": "شو  نوع موبايلك؟ \nبتحب تعرف أخبار #فلسطين و #المقاومة ومش مرتاح لكثرة الأخبار في التويتر والفيس؟\nشوف الرابط... http://t.co/AyI94RKp8m",
		"created_at": "2014-02-27T16:49:31+00:00",
		"like_count": 0,
		"retweet_count": 1,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "556898631890915330",
		"text": "#صورة \nمن تشييع الشهيد سامي الجعار بمدينة راهط في #النقب مساء اليوم http://t.co/Svt1bkKLzI",
		"created_at": "2015-01-18T19:39:15+00:00",
		"like_count": 5,
		"retweet_count": 5,
		"reply_count": 1,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "1334240929570455554",
		"text": "🎨 Entrer dans #Noël à la lumière des églises romaines.\n\n📅 Chaque vendredi de l’#Avent, Vatican News propose une échappée de foi et beauté dans l’une des mille églises de Rome, à la découverte des représentations de la Nativité.\n\n👉 RDV le 4 décembre sur https://t.co/3oB8u8NIfo https://t.co/1Ohc6ILQdS",
		"created_at": "2020-12-02T21:00:01+00:00",
		"like_count": 48,
		"retweet_count": 10,
		"reply_count": 2,
		"view_count": 0,
		"username": "vaticannews_fr",
		"fullname": "Vatican News",
		"category": "religious-referential"
	},
	{
		"id": "2036873741284606204",
		"text": "هل حقًّا الإمام الشافعي أول من غيَّر معنى \"الصراط المستقيم\" ليصبح طريقًا يمشي عليه الناس يوم القيامة؟!\n\nد. محمد عبودة\nمدرس بكلية الدعوة الإسلامية\nعضو مرصد الأزهر لمكافحة التطرف\n\n#وعي https://t.co/49SwQMfpUv",
		"created_at": "2026-03-25T18:31:57+00:00",
		"like_count": 86,
		"retweet_count": 16,
		"reply_count": 9,
		"view_count": 6720,
		"username": "AlAzhar",
		"fullname": "الأزهر الشريف",
		"category": "religious-referential"
	},
	{
		"id": "1677027180394561538",
		"text": "🔽 Foreign ministers of the Islamic Republic of Iran and the Arab Republic of Syria hold talks on the sidelines of the NAM top diplomats meeting in Baku https://t.co/1rYX8R7fHb",
		"created_at": "2023-07-06T18:50:12+00:00",
		"like_count": 32,
		"retweet_count": 2,
		"reply_count": 3,
		"view_count": 4378,
		"username": "IRIMFA_EN",
		"fullname": "Foreign Ministry, Islamic Republic of Iran",
		"category": "diplomatic-relational"
	},
	{
		"id": "774748728909565953",
		"text": "استشهاد طفلة دهسها مستوطن جنوب بيت لحم https://t.co/5n0oQRoUwW",
		"created_at": "2016-09-10T23:17:45+00:00",
		"like_count": 4,
		"retweet_count": 3,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "976765417908776963",
		"text": "Crazy Joe Biden is trying to act like a tough guy. Actually, he is weak, both mentally and physically, and yet he threatens me, for the second time, with physical assault. He doesn’t know me, but he would go down fast and hard, crying all the way. Don’t threaten people Joe!",
		"created_at": "2018-03-22T10:19:57+00:00",
		"like_count": 164597,
		"retweet_count": 43001,
		"reply_count": 68210,
		"view_count": 0,
		"username": "realDonaldTrump",
		"fullname": "Donald J. Trump",
		"category": "religious-referential"
	},
	{
		"id": "977278827197067264",
		"text": "Can #Christians Support #GinaHaspel, a “Torturer,” as #CIA Director? | https://t.co/RWadExY5N1 by Daniel Strand via @ProvMagazine @ASU_SHPRS #Haspel #Ethics #Christianity #Religion #Politics #FaithFriday",
		"created_at": "2018-03-23T20:20:04+00:00",
		"like_count": 2,
		"retweet_count": 3,
		"reply_count": 1,
		"view_count": 0,
		"username": "TheIRD",
		"fullname": "IRD",
		"category": "religious-referential"
	},
	{
		"id": "917834213310763008",
		"text": "ذكرى تنفيذ الشهيد اسحاق بدران عملية طعن بالمصرارة بالقدس المحتلة https://t.co/3Haf0BZxf7",
		"created_at": "2017-10-10T19:28:23+00:00",
		"like_count": 2,
		"retweet_count": 2,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "diplomatic-relational"
	},
	{
		"id": "1842881436417700033",
		"text": "The Palestinian ppl have the right to stand against an enemy that has seized their land. Those who support Palestinian ppl are fulfilling their duty. No one has the right to object to Lebanese ppl and Hezbollah supporting Gaza. It is their duty, and they should have done this.",
		"created_at": "2024-10-06T10:55:48+00:00",
		"like_count": 3987,
		"retweet_count": 706,
		"reply_count": 518,
		"view_count": 245538,
		"username": "khamenei_ir",
		"fullname": "Khamenei.ir",
		"category": "digital-influential"
	},
	{
		"id": "1101931872840495104",
		"text": "#صور.. رئيس المكتب السياسي لحركة حماس إسماعيل هنية في زيارة لعائلة الشاب عبد الدايم أبو لبدة للتهنئة بالإفراج عنه من السجون المصرية https://t.co/R6NnlZE251",
		"created_at": "2019-03-02T19:46:46+00:00",
		"like_count": 5,
		"retweet_count": 0,
		"reply_count": 0,
		"view_count": 0,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "religious-referential"
	},
	{
		"id": "2059272068814815463",
		"text": "بمتابعة وتوجيه معالي وزير الشؤون الإسلامية والدعوة والإرشاد الشيخ الدكتور عبداللطيف بن عبدالعزيز آل الشيخ، أكملت الوزارة جاهزية #مسجد_المشعر_الحرام بـ #مزدلفة؛ لاستقبال ضيوف الرحمن مساء اليوم لأداء صلاتي المغرب والعشاء جمعًا وقصرًا، عبر منظومة متكاملة من الخدمات التشغيلية والتوعوية؛ بما يسهم في أداء الحجاج نسكهم بيسر وطمأنينة.\n\n#حياكم_الله",
		"created_at": "2026-05-26T13:54:55+00:00",
		"like_count": 50,
		"retweet_count": 28,
		"reply_count": 0,
		"view_count": 15572,
		"username": "Saudi_Moia",
		"fullname": "وزارة الشؤون الإسلامية 🇸🇦",
		"category": "diplomatic-relational"
	},
	{
		"id": "2042679507027660915",
		"text": "Jerusalem’s holy sites have reopened across the Old City.\n\nAfter weeks of missile threats from the Iranian Regime that forced closures and restrictions, worshippers are now able to return to places sacred to all faiths.\n\nWe’re especially proud to welcome Christian worshippers back this weekend for the Holy Fire ceremony at the Church of the Holy Sepulchre - a moment of faith, tradition, and light returning to Jerusalem.\n\n🎥 @israelpolice",
		"created_at": "2026-04-10T19:02:00+00:00",
		"like_count": 194,
		"retweet_count": 44,
		"reply_count": 3,
		"view_count": 3282,
		"username": "IsraelinUSA",
		"fullname": "Embassy of Israel to the USA",
		"category": "religious-referential"
	},
	{
		"id": "1933885108722761980",
		"text": "RT @site_khamenei: 🎥  | الغدير يوم يأس الكفّار من القضاء على الإسلام https://t.co/5LoSNWKIDJ",
		"created_at": "2025-06-14T13:51:54+00:00",
		"like_count": 0,
		"retweet_count": 783,
		"reply_count": 0,
		"view_count": 5,
		"username": "ar_khamenei",
		"fullname": "الإمام الخامنئي",
		"category": "diplomatic-relational"
	},
	{
		"id": "1406934667887054849",
		"text": "🔴#LIVE: Russian Foreign Minister Sergey #Lavrov and #OSCE Secretary General @HelgaSchmid_SG hold a joint press-conference following talks in #Moscow.\n\n#RussiaOSCE\n\nhttps://t.co/hobOWgtV7b",
		"created_at": "2021-06-21T11:18:59+00:00",
		"like_count": 22,
		"retweet_count": 12,
		"reply_count": 1,
		"view_count": 0,
		"username": "mfa_russia",
		"fullname": "MFA Russia 🇷🇺",
		"category": "digital-influential"
	},
	{
		"id": "1690825319496687616",
		"text": "اختتام جلسات اليوم الأول للمؤتمر الدولي \"#تواصل_وتكامل\" الذي تنظمه وزارة الشؤون الإسلامية والدعوة والإرشاد، في مكة المكرمة.\n\nhttps://t.co/WFxHIzhoV0",
		"created_at": "2023-08-13T20:39:04+00:00",
		"like_count": 28,
		"retweet_count": 16,
		"reply_count": 5,
		"view_count": 12104,
		"username": "Saudi_Moia",
		"fullname": "وزارة الشؤون الإسلامية 🇸🇦",
		"category": "diplomatic-relational"
	},
	{
		"id": "1044940012926775296",
		"text": ".@SecPompeo also discussed the pressure campaign on #Iran's regime during his interview with @CBSThisMorning: \"European businesses are voting with their checkbooks. They are leaving Iran in droves.\"",
		"created_at": "2018-09-26T13:21:27+00:00",
		"like_count": 225,
		"retweet_count": 73,
		"reply_count": 14,
		"view_count": 0,
		"username": "StateDept",
		"fullname": "Department of State",
		"category": "digital-influential"
	},
	{
		"id": "602868843573194754",
		"text": "Thank God for all who died to protect our earthly freedom &amp; for Jesus Who gave His life so we might have eternal freedom w/Him. #MemorialDay",
		"created_at": "2015-05-25T16:08:27+00:00",
		"like_count": 1281,
		"retweet_count": 774,
		"reply_count": 29,
		"view_count": 0,
		"username": "Franklin_Graham",
		"fullname": "Franklin Graham",
		"category": "religious-referential"
	},
	{
		"id": "1937482998087299358",
		"text": "وزير الخزانة، سكوت بيسنت: من خلال رؤيته المتمثّلة في تحقيق السلام عبر القوة، حقّق الرئيس ترامب انتصارًا تاريخيًا آخر للشعب الأمريكي من شأنه تعزيز أمن أمّتنا والأمن العالمي. يتم الوفاء بالوعود التي قُطعت.",
		"created_at": "2025-06-24T12:08:38+00:00",
		"like_count": 5,
		"retweet_count": 0,
		"reply_count": 1,
		"view_count": 3871,
		"username": "USAbilAraby",
		"fullname": "الخارجية الأمريكية",
		"category": "diplomatic-relational"
	},
	{
		"id": "1065615095437377536",
		"text": "#Anapa: End of year meeting with Defence Ministry leadership and defence industry heads https://t.co/6R3i6eeZJE https://t.co/mmSkwXaVi7",
		"created_at": "2018-11-22T14:36:51+00:00",
		"like_count": 160,
		"retweet_count": 51,
		"reply_count": 12,
		"view_count": 0,
		"username": "KremlinRussia_E",
		"fullname": "President of Russia",
		"category": "diplomatic-relational"
	},
	{
		"id": "1369173605397852166",
		"text": "💫 LE SAINT DU JOUR | Mardi 9 mars\n\nSainte Françoise, romaine, fondatrice des Oblates de Tor de' Specchi (1384-1440) \n\nL'une des Saintes de la charité les plus connues de l’Église, elle choisit le bien comme but de la vie par amour pour le Christ.  https://t.co/vxQzvt2npS https://t.co/Ujr7M9z9xk",
		"created_at": "2021-03-09T06:30:00+00:00",
		"like_count": 25,
		"retweet_count": 10,
		"reply_count": 0,
		"view_count": 0,
		"username": "vaticannews_fr",
		"fullname": "Vatican News",
		"category": "religious-referential"
	},
	{
		"id": "1836339940830990558",
		"text": "🔴 #LIVE: IV Eurasian Women's Forum Opening Ceremony – Plenary Session 'Women For Strengthening Trust and Global Cooperation' https://t.co/FVYhw17Ad3",
		"created_at": "2024-09-18T09:42:14+00:00",
		"like_count": 151,
		"retweet_count": 44,
		"reply_count": 37,
		"view_count": 13433,
		"username": "mfa_russia",
		"fullname": "MFA Russia 🇷🇺",
		"category": "diplomatic-relational"
	},
	{
		"id": "1691510918662811648",
		"text": "صدق او لا تصدق\nسفير بريطانيا السابق في السعودية بعد تجربته مع العرب يقول :\"مخ العرب فاضي\". https://t.co/aKFN7LkQoR",
		"created_at": "2023-08-15T18:03:24+00:00",
		"like_count": 118,
		"retweet_count": 14,
		"reply_count": 159,
		"view_count": 68917,
		"username": "EdyCohen",
		"fullname": "إيدي كوهين אדי כהן 🇮🇱",
		"category": "diplomatic-relational"
	},
	{
		"id": "1607460642323333120",
		"text": "مشاهد جوية لمدينة غزة تزامنا مع أجواء المنخفض الجوي الذي يضرب البلاد https://t.co/JsvGEf51gb",
		"created_at": "2022-12-26T19:37:36+00:00",
		"like_count": 2,
		"retweet_count": 0,
		"reply_count": 0,
		"view_count": 968,
		"username": "PalinfoAr",
		"fullname": "المركز الفلسطيني للإعلام",
		"category": "digital-influential"
	},
	{
		"id": "1892910239789338956",
		"text": "🇱🇧Depuis le Liban, le cardinal Bechara Raï, patriarche des Maronites revient sur le travail de l'Église pour la stabilité dans le pays et la paix nécessaire pour la région\nhttps://t.co/3Z3VBiwCux",
		"created_at": "2025-02-21T12:12:24+00:00",
		"like_count": 14,
		"retweet_count": 4,
		"reply_count": 1,
		"view_count": 990,
		"username": "vaticannews_fr",
		"fullname": "Vatican News",
		"category": "diplomatic-relational"
	},
	{
		"id": "1266358851340828672",
		"text": "بمزيد من الرضا بقضاء الله وقدره، يحتسب #الأزهر الشريف عند الله تعالى، العالم الجليل أ.د/ عبد العزيز سيف النصر، عضو #هيئة_كبار_العلماء بالأزهر، أستاذ العقيدة والفلسفة بجامعة الأزهر، والذي وافته المنية صباح اليوم الجمعة عن عمر ناهز ال ٨٤ عامًا https://t.co/AOKvRRG3ax",
		"created_at": "2020-05-29T13:20:52+00:00",
		"like_count": 733,
		"retweet_count": 71,
		"reply_count": 66,
		"view_count": 0,
		"username": "AlAzhar",
		"fullname": "الأزهر الشريف",
		"category": "religious-referential"
	},
	{
		"id": "1415982908226080770",
		"text": "Prime Minister Naftali Bennett spoke today with South Korean President Moon Jae-in, who congratulated him on assuming office and conveyed his best wishes for continued social stability and prosperity during his tenure. 🇮🇱🇰🇷 \n\nhttps://t.co/CrAHrT1sc3",
		"created_at": "2021-07-16T10:33:27+00:00",
		"like_count": 130,
		"retweet_count": 15,
		"reply_count": 11,
		"view_count": 0,
		"username": "IsraeliPM",
		"fullname": "Prime Minister of Israel",
		"category": "diplomatic-relational"
	}
];
